In [1]:
import numpy as np
import pymc3 as pm
import matplotlib.pyplot as plt
import pandas as pd
import json
from IPython.display import display, Math, Latex

In [36]:
model1_description = """Distributions and inter distances of TCR and CD45 molecules
that result from the early contact of a T cell and APC (Antigen Presenting Cell)."""

class model:
    def __init__(self,shortName,longName,description,index,D,H,Tu,Tt):
        self.shortName = shortName # str
        self.longName = longName # str
        self.description = description # str
        self.index = index # int
        self.D = D # pd.dataFrame
        self.H = H # json
        self.Tu = Tu # table
        self.Tt = Tt # table

In [37]:
model1 = model(shortName = 'KS',
               longName = 'Kinetic segregation',
               description = model1_description,
               index = 1,
               D = [],
               H = [],
               Tu = [],
               Tt = [])

In [5]:
class rv:
    def __init__(self,type2,name,description,distribution,distributionParameters,units):
        self.type2 = type2 # str
        self.name = name # str
        self.description = description # str
        self.distribution = distribution # 
        self.distributionParameters = distributionParameters
        self.units = units

In [26]:
# define depletion table
t = rv(type2 = 'Free parameter',
       name = '$$t^{KS}$$',
       description = 'Time',
       distribution = '$$Uniform(lower,upper)$$',
       distributionParameters = [0, 100],
       units = '$$sec$$') # choose from pm list

k = rv(type2 = 'Free parameter',
       name = '$$\kappa^{KS}$$',
       description = 'Membrane rigidity',
       distribution = '$$Normal(\mu,\sigma)$$',
       distributionParameters = [50., 20.],
       units = '$$kTnm^2$$') # choose from pm list  

dep_intercept = rv(type2 = 'Random variable',
       name = '$$dep^{KS}_{intercepct}$$',
       description = 'Intercept of linear plain',
       distribution = '$$Normal(\mu,\sigma)$$',
       distributionParameters = [100., 50.],
       units = '$$nm$$') # # choose from pm list 

dep_tSlope = rv(type2 = 'Random variable',
       name = '$$dep^{KS}_{tSlope}$$',
       description = 'Plain slope for t',
       distribution = '$$Normal(\mu,\sigma)$$',
       distributionParameters = [0., 1.],
       units = '$$-$$') # # choose from pm list 

dep_kSlope = rv(type2 = 'Random variable',
       name = '$$dep^{KS}_{kSlope}$$',
       description = 'Plain slope for k',
       distribution = '$$Normal(\mu,\sigma)$$',
       distributionParameters = [0., 1.],
       units = '$$-$$') # # choose from pm list 

dep = rv(type2 = 'Output',
       name = '$$dep^{KS}$$',
       description = 'Depletion distance between TCR and CD45',
       distribution = '$$Normal(\mu,\sigma)$$',
       distributionParameters = [200., 50.],
       units = '$$nm$$') # # choose from pm list

In [40]:
def model1_dep_untrained_table(): # by row

    info = [
        {'Type': t.type2,
         'Name': t.name,
         'Distribution': t.distribution,
         'Distribution parameters': t.distributionParameters,
         'Units': t.units},
        
        {'Type': k.type2,
         'Name': k.name,
         'Distribution': k.distribution,
         'Distribution parameters': k.distributionParameters,
         'Units': k.units},
        
        {'Type': dep_intercept.type2,
         'Name': dep_intercept.name,
         'Distribution': dep_intercept.distribution,
         'Distribution parameters': dep_intercept.distributionParameters,
         'Units': dep_tSlope.units},
        
        {'Type': dep_tSlope.type2,
         'Name': dep_tSlope.name,
         'Distribution': dep_tSlope.distribution,
         'Distribution parameters': dep_tSlope.distributionParameters,
         'Units': dep_tSlope.units},
        
        {'Type': dep_kSlope.type2,
         'Name': dep_kSlope.name,
         'Distribution': dep_kSlope.distribution,
         'Distribution parameters': dep_kSlope.distributionParameters,
         'Units': dep_kSlope.units},
        
        {'Type': dep.type2,
         'Name': dep.name,
         'Distribution': dep.distribution,
         'Distribution parameters': dep.distributionParameters,
         'Units': dep.units}
    ]
    
    table = pd.DataFrame(info, index=['t', 'k', 'intercept', 'tSlope', 'kSlope', 'Output'])
    
    return table

model1_dep_untrained_table()
model1_dep_untrained_table().style.set_properties(**{'text-align': 'left',
                                       'border-style': 'solid',
                                       'border-width': 0.25,
                                       'background-color': 'rgba(200, 150, 255, 0.75)'})

In [81]:
def model1_table(): # by column
    info = {'Type': [t.type2,
                     k.type2,
                     dep_intercept.type2,
                     dep_tSlope.type2,
                     dep_kSlope.type2,
                     dep.type2],
            'Name': [t.name,
                     k.name,
                     dep_intercept.name,
                     dep_tSlope.name,
                     dep_kSlope.name,
                     dep.name],
            'Description':[t.description,
                           k.description,
                           dep_intercept.description,
                           dep_tSlope.description,
                           dep_kSlope.description,
                           dep.description],
            'Distribution':[t.distribution,
                            k.distribution,
                            dep_intercept.distribution,
                            dep_tSlope.distribution,
                            dep_kSlope.distribution,
                            dep.distribution],
           'Distribution parameters':[t.distributionParameters,
                                      k.distributionParameters,
                                      dep_intercept.distributionParameters,
                                      dep_tSlope.distributionParameters,
                                      dep_kSlope.distributionParameters,
                                      dep.distributionParameters],
           'Units':[t.units,
                    k.units,
                    dep_intercept.units,
                    dep_tSlope.units,
                    dep_kSlope.units,
                    dep.units]}

    table = pd.DataFrame(info)
    
    return table

model1_table()
model1_table().style.set_properties(**{'text-align': 'left',
                                       'border-style': 'solid',
                                       'border-width': 0.25,
                                       'background-color': 'rgba(200, 150, 255,0.3)'}) # (0.1, 0.2, 0.5) #'#3f3f3f'

In [ ]:
# df = pd.DataFrame(list_of_dict,
#                   index=['a', 'b', 'c', 'd'],
#                   columns=['Age', 'Marks', 'Name', 'Address'])